### ISSUE TITLE
[Crashes] when enabling the switch themes

### ISSUE THREAD

**Issue by danielaniq28** [TheOrionTrain/Cemu-UI#1]
Error Logs.

System.IO.IOException: The volume does not contain a recognized file system.
Please make sure that all required file system drivers are loaded and that the volume is not corrupted.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
   at System.IO.File.ReadAllBytes(String path)
   at Cemu_UI.Game.getHash()
   at NintendoSwitchTheme.Managers.SaveManager.getSaveSize(Game game)
   at SwitchTheme.Main.MenuLoaded(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at Cemu_UI.EventManager.OnMenuLoaded()
   at Cemu_UI.Main.browserInitialized(Object sender, LoadingStateChangedEventArgs e)
   at CefSharp.WinForms.ChromiumWebBrowser.CefSharp.Internals.IWebBrowserInternal.SetLoadingStateChange(LoadingStateChangedEventArgs args)
   at CefSharp.Internals.ClientAdapter.OnLoadingStateChange(ClientAdapter* , CefRefPtr<CefBrowser>* browser, Boolean isLoading, Boolean canGoBack, Boolean canGoForward)

**Comment by SeanPost** [comment]
Is there a fix for this issue.. I have same problem
